### ISSUE TITLE
Phone has no network connection from the sim card

### ISSUE THREAD

**Issue by SirLenskjold** [maetl/calyx#30]
My mobile Pixel 6, android vision 13, calyxOS vision 4.5.1
It just says "Phone not allowed for voice"
After that, no network is available.
Started about a month ago, with only once in a while.
But now I can hardly use my phone as it can hardly ever get a network connection via my sim card.
Pulling my sim card out of the phone and putting it back in sometimes works.

**Comment by maetl** [comment]
This is a generative text tool for creative coding and art. calyxOS is a completely different project with no relationship to us. 

Please go to their website and look for their official bug reporting/support process—they will hopefully have some useful guidelines about how to get help!

**Comment by SirLenskjold** [comment]
sorry
